spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql
    url: jdbc:mysql://localhost:3306/shop?autoReconnect=true&useSSL=false
security:
  oauth2:
    client:
      client-id: admin
      client-secret: secret
      refresh-token-validity-seconds: 86400
      access-token-validity-seconds: 3600

